# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  allowed_user_domain: 'organicadigital.com'
  secret_key_base: 0d624a0b6777c4926574eb2255318ae0e33e979879c9ef254614a81f8834464c20b641d202d227e8e0690aa95e98499bf2d02e6044f8e80aa5d67d52b26d8185
   action_mailer:
    default_url_options:
      host: localhost
      port: 3000
    smtp_settings:
      address: localhost
      port: 1025

test:
  allowed_user_domain: 'organicadigital.com'
  secret_key_base: db02a549008e572fb84ad79634eb65c4c83649da8a651b18f27adddf4a65e964b193b76f7b1b3f000e86b7f8e5fa1de9c665b394520f6d5f428b90cc5f57a4a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  allowed_user_domain: <%= ENV["ALLOWED_USER_DOMAIN"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  action_mailer:
    default_url_options:
      host: <%= ENV['HOST'] %>
      port: <%= ENV['PORT'] %>
      protocol: <%= ENV['PROTOCOL'] %>
    smtp_settings:
      address: 'smtp.sendgrid.net'
      port: 587
      domain: 'heroku.com'
      user_name: <%= ENV['SENDGRID_USERNAME'] %>
      password: <%= ENV['SENDGRID_PASSWORD'] %>
      authentication: plain
      enable_starttls_auto: true


